[General]
ReportStats=false

[UdpEndpoint drone1]
Device=/dev/ttyACM0
Baud=57600
AllowSrcSysIn = 1
BlockSrcSysIn = 2
BlockSrcSysIn = 3

[UdpEndpoint drone2]
Device=/dev/ttyACM1
Baud=57600
AllowSrcSysIn = 2
BlockSrcSysIn = 1
BlockSrcSysIn = 3

[UdpEndpoint whiteboat]
Device=/dev/ttyACM2
Baud=57600
AllowSrcSysIn = 3
BlockSrcSysIn = 1
BlockSrcSysIn = 2

[UdpEndpoint gcs1]
Mode = normal
Address = 127.0.0.1
Port = 14553
AllowSrcSysOut = 1
BlockSrcSysOut = 2
BlockSrcSysOut = 3

[UdpEndpoint gcs2]
Mode = normal
Address = 127.0.0.1
Port = 14554
AllowSrcSysOut = 2
BlockSrcSysOut = 1
BlockSrcSysOut = 3

[UdpEndpoint gcs3]
Mode = normal
Address = 127.0.0.1
Port = 14558
AllowSrcSysOut = 3
BlockSrcSysOut = 1
BlockSrcSysOut = 2